create table jobs2 (Job_id VARCHAR2(10 BYTE) PRIMARY KEY, job_title VARCHAR2(35 BYTE), min_salary NUMBER(6,0),max_salary NUMBER(6,0));
create table job_history2 (emp_id NUMBER(6,0), start_date DATE, end_date DATE,job_id1 VARCHAR2(10 BYTE),dep_id NUMBER(4,0));
alter table jobs2 modify Job_id NUMBER(6,0);
alter table job_history2 modify Job_id1 NUMBER(6,0);
insert into jobs2 values (1223,'President',25000,25000);
alter table job_history2 ADD foreign key (job_id1) references jobs2(Job_id);
insert into jobs2 values (2234,'yes',122,334);
alter table jobs2 add (Job_Nature  VARCHAR2(10 BYTE));
create table replica as select * from HR.EMPLOYEES;
select * from replica;
create table newemp as select * from EMPLOYEES;
select * from newemp;
alter table job_history2 add (employee_id NUMBER(6,0));
alter table job_history2 ADD foreign key (emp_id) references EMPLOYEES(employee_id);
alter table jobs2 drop column Job_Nature;
alter table newemp add constraint first_name check(upper(first_name)=first_name);
alter table newemp add constraint salary Unique(salary);
alter table newemp modify Phone_number varchar(20) not null;
insert into newemp (employee_id, first_name, last_name, email, phone_number, hire_date, job_id, salary, commission_pct, manager_id, department_id) values (1111,'yes','no','ok',12223,'12-DEC-02','AD_PES',12313,null,444,667);
update newemp set salary=8000 where employee_id=105 and salary<10000;
alter table newemp add constraint pk_employee_job PRIMARY KEY (employee_id, job_id);
create index indx_job_id on job_history2(job_id1);
drop table newemp;